### ISSUE TITLE
[BUG]: rdcman: unexpected switch: /accepteula

### ISSUE THREAD

**Issue by boozedog** [niheaven/scoop-sysinternals#13]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

rdcman

### Expected/Current Behaviour

When I attempt to start rdcman after installing from scoop I get the following:

![image](https://github.com/niheaven/scoop-sysinternals/assets/1410808/7caf7169-5e92-4a37-95b6-46bd9ca9c41a)

### Steps to Reproduce

```console
N/A
```

### Possible Solution

N/A

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
49b46fcb7 (HEAD -> master, origin/master, origin/HEAD) linphone: Update to version 5.1.0

'main' bucket:
57cbfa46f (HEAD -> master, origin/master, origin/HEAD) terraform-provider-ibm: Update to version 1.56.1

'sysinternals' bucket:
db7ddd5 (HEAD -> main, origin/main, origin/HEAD) zoomit: Update to version 7.1
```
```


### Scoop Config

```console
❯ scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-08-21T08:59:15.0994514-04:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
N/A
```

**Comment by niheaven** [comment]
Fixed by 062afe4
